[package]
name = "slhdsa-c-rs"
version = "0.0.1"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = "0.72.1"
cc = "1.2.35"
glob = "0.3.3"

[dev-dependencies]
env_logger = "0.11.8"
log = "0.4.28"
anyhow = "1.0.99"
rand = { version = "0.9.2", features = ["std_rng"] }

[workspace]
